### ISSUE TITLE
表面带下划线，tableName未自动过滤下划线

### ISSUE THREAD

**Issue by 13815253970** [wangguanquan/bree-mybatis-maven-plugin#55]
例如表名：sale_category
生成的名称： Sale_category
${dao.tableName!?lower_case?capitalize}

**Comment by wangguanquan** [comment]
如下两种方式可以修复此问题
1. 使用entryName代替tableName，示例代码：`${dao.entryName!?cap_first}`
2. `<#import "../lib/lib.ftl" as lib/>` 然后使用`lib.toCamelCase(dao.tableName)?cap_first`
